### ISSUE TITLE
Not working with mri-2.2.0dev

### ISSUE THREAD

**Issue by RoxasShadow** [DAddYE/foreverb#31]
I had to switch to mri-2.1.1, since whenever I run a script based to foreverb, it dies raising the following stack trace:

```
[miyuki] Pid not found, process seems doesn't exist!
[miyuki] Process daemonized with pid 44416 with thread and Forever v.0.3.2
/Users/giovanni/.rvm/gems/ruby-head/gems/foreverb-0.3.2/lib/forever/base.rb:76:in `trap': Invalid argument - SIGKILL (Errno::EINVAL)
	from /Users/giovanni/.rvm/gems/ruby-head/gems/foreverb-0.3.2/lib/forever/base.rb:76:in `block (2 levels) in initialize'
	from /Users/giovanni/.rvm/gems/ruby-head/gems/foreverb-0.3.2/lib/forever/base.rb:76:in `each'
	from /Users/giovanni/.rvm/gems/ruby-head/gems/foreverb-0.3.2/lib/forever/base.rb:76:in `block in initialize'
	from /Users/giovanni/.rvm/gems/ruby-head/gems/foreverb-0.3.2/lib/forever/base.rb:349:in `fork'
	from /Users/giovanni/.rvm/gems/ruby-head/gems/foreverb-0.3.2/lib/forever/base.rb:349:in `maybe_fork'
	from /Users/giovanni/.rvm/gems/ruby-head/gems/foreverb-0.3.2/lib/forever/base.rb:69:in `initialize'
	from /Users/giovanni/.rvm/gems/ruby-head/gems/foreverb-0.3.2/lib/forever.rb:18:in `new'
	from /Users/giovanni/.rvm/gems/ruby-head/gems/foreverb-0.3.2/lib/forever.rb:18:in `run'
	from /Users/giovanni/.rvm/gems/ruby-head/gems/miyuki-0.5.1/bin/miyuki:26:in `<top (required)>'
	from /Users/giovanni/.rvm/gems/ruby-head/bin/miyuki:23:in `load'
	from /Users/giovanni/.rvm/gems/ruby-head/bin/miyuki:23:in `<main>'
	from /Users/giovanni/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
	from /Users/giovanni/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
```

Tests pass though.

**Comment by scythargon** [comment]
+1 here
@RoxasShadow any luck with this problem?

**Comment by Exoth** [comment]
I've got this problem too. Isn't SIGKILL untrappable? I think, that earlier there just wasn't any check in ruby for invalid signals, and now from ruby 2.2.0 there is the check. I'm going to make a pull request with just a removal of KILL from the array of trapped signals.

**Comment by DAddYE** [comment]
Thanks @Exoth. I already published it on rubygems.
