### ISSUE TITLE
`require': cannot load such file -- forever (LoadError)

### ISSUE THREAD

**Issue by PeterDavidCarter** [DAddYE/foreverb#41]
I have installed the forever gem and created a script exactly the same as the script in the readme (called it `serverb`):

```
#!/usr/bin/ruby
require 'rubygems' unless defined?(Gem)
require 'forever'
require 'mail'

Forever.run do
  ##
  # You can set these values:
  #
  # dir  "foo"     # Default: File.expand_path('../../', __FILE__)
  # file "bar"     # Default: __FILE__
  # log  "bar.log" # Default: File.expand_path(dir, '/log/[file_name].log')
  # pid  "bar.pid" # Default: File.expand_path(dir, '/tmp/[file_name].pid')
  #

  on_error do |e|
    Mail.deliver do
      delivery_method :sendmail, :location => `which sendmail`.chomp
      to      "d.dagostino@lipsiasoft.com"
      from    "exceptions@lipsiasoft.com"
      subject "[Foo Watcher] #{e.message}"
      body    "%s\n  %s" % [e.message, e.backtrace.join("\n  ")]
    end
  end

  before :each do # or if you prefer before :all
    require 'bundler/setup'
    require 'foo'
    Foo.start_loop
  end
end
```

 in the `bin` folder of my project directory, but am still getting the error:

```
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- forever (LoadError)
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from bin/serverb:3:in `<main>'

```

when I run `bin/serverb`.

**Comment by jimedelstein** [comment]
Same issue here
